grails-app/controllers/com/rs/gral/RsGralEstadoController.groovy
package com.rs.gral

/**
 * RsGralEstadoController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
class RsGralEstadoController {

    static scaffold = true
//	def index = { }
}

grails-app/controllers/com/rs/gral/RsGralPaisController.groovy
package com.rs.gral

/**
 * RsGralPaisController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
class RsGralPaisController {

    static scaffold = true
//	def index = { }
}

grails-app/controllers/com/rs/gral/RsPersonaController.groovy
package com.rs.gral

/**
 * RsPersonaController
 * A controller class handles incoming web requests and performs actions such as redirects, rendering views and so on.
 */
class RsPersonaController {

    static scaffold = true
//	def index = { }
}

grails-app/views/_menu/_admin.gsp
<li class="dropdown">
	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
   		<i class="glyphicon glyphicon-wrench"></i>
		<g:message code="default.admin.label"/><b class="caret"></b>
	</a>
	<ul class="dropdown-menu">
		<li class="">
			<a tabindex="-1" href="#"><b>Technical Admin</b></a>
		</li>
		<g:if env="development">
		<li class="">
			<a href="${createLink(uri: '/dbconsole')}">
				<i class="glyphicon glyphicon-dashboard"></i>
				<g:message code="default.dbconsole.label"/>
			</a>
		</li>
		</g:if>
		<li class="">
			<a href="${createLink(uri: '/systeminfo')}">
				<i class="glyphicon glyphicon-info-sign"></i>
				<g:message code="default.systeminfo.label"/>
			</a>
		</li>
	</ul>
</li>

grails-app/views/_menu/_controller.gsp
<li class="dropdown">
	<a class="dropdown-toggle" data-toggle="dropdown" href="#">Browse <b class="caret"></b></a>
	<ul class="dropdown-menu">
		<g:each var="c" in="${grailsApplication.controllerClasses.sort { it.fullName } }">
			<li class="controller">
				<g:link controller="${c.logicalPropertyName}">
					<g:if test="${c.fullName.contains('HomeController')}">
						<i class="glyphicon glyphicon-home"></i>
					</g:if>
					<g:elseif test="${c.fullName.contains('DemoPageController')}">
						<i class="glyphicon glyphicon-list-alt"></i>
					</g:elseif>
					<g:elseif test="${c.fullName.contains('DbdocController')}">
						<i class="glyphicon glyphicon-cloud"></i>
					</g:elseif>
					${c.fullName.substring(c.fullName.lastIndexOf('.')+1)}
				</g:link>
			</li>
		</g:each>
	</ul>
</li>

grails-app/views/_menu/_info.gsp
<li class="dropdown dropdown-btn">
	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
   		<i class="glyphicon glyphicon-info-sign"></i>
		<g:message code="default.info.label"/> <b class="caret"></b>
	</a>
	
	<ul class="dropdown-menu">
		<%-- Note: Links to pages without controller are redirected in conf/UrlMappings.groovy --%>
		<li class="">
			<a href="${createLink(uri: '/about')}">
				<i class="glyphicon glyphicon-info-sign"></i>
				<g:message code="default.about.label"/>
			</a>
		</li>
		<li class="">
			<a href="http://wordpress.com/signup/">
				<i class="glyphicon glyphicon-align-justify"></i>
				<i><g:message code="default.blog.label"/></i>
			</a>
		</li>
		<li class="">
			<a href="${createLink(uri: '/terms')}">
				<i class="glyphicon glyphicon-exclamation-sign"></i>
				<g:message code="default.terms.label"/>
			</a>
		</li>
		<li class="">
			<a href="${createLink(uri: '/contact')}">
				<i class="glyphicon glyphicon-envelope"></i>
				<g:message code="default.contact.label"/>
			</a>
		</li>
	</ul>
</li>

grails-app/views/_menu/_language.gsp
<g:set var="lang" value="${session.'org.springframework.web.servlet.i18n.SessionLocaleResolver.LOCALE' ?: org.springframework.web.servlet.support.RequestContextUtils.getLocale(request).toString().substring(0,2)}"/>
<g:set var="currentURL" value="${request.forwardURI}"/>

<%--<ul class="nav secondary-nav language-dropdown pull-right">--%>
	<li class="dropdown dropdown-btn js-language-dropdown">
		<a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="javascript:;">
			<img class="" src="${resource(plugin: 'kickstart', dir: 'images/flags',file: lang.toString()+'.png')}" />
		</a>
		<ul class="dropdown-menu dropdown-menu-dark" role="menu">

			<!-- assuming that the default locale is English -->
			<li><a class="js-language-link" title="English" data-lang-code="en" href="${currentURL+'?lang=en'}">
				<img class="" src="${resource(plugin: 'kickstart', dir: 'images/flags',file: 'en.png')}"/>
				<g:message code="language.en" default="en"/> ${currentlURL }
			</a></li>

			<li class="divider"></li>

			<!-- get list of all locales available due to an existing property-file in /grails-app/i18n (set once in Bootstrap.groovy) -->
			<g:set var="allLocales" value="${grailsApplication.config.grails.i18n.locales}"/>
			<g:each status="i" var="locale" in="${allLocales}">
				<li><a class="js-language-link" title="${message(code: 'language.'+locale, default: locale)}" data-lang-code="${locale}" href="${currentURL+'?lang='+locale}">
					<img class="" src="${resource(plugin: 'kickstart', dir: 'images/flags',file: locale+'.png')}"/>
					<g:message code="language.${locale}" default="${locale}"/>
				</a></li>
			</g:each>

		</ul>
	</li>
<%--</ul>--%>

grails-app/views/_menu/_menu.gsp
<%@ page import="com.rs.seguridad.Usuario" %>
<g:set var="usuario" value="${Usuario.findByUsername(sec.loggedInUserInfo(field:'username'))}"/>

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Catálogos</a>
            <ul class="dropdown-menu">
                <li class="dropdown-submenu">
                    <a tabindex="-1" href="#">RS</a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-submenu">
                            <a href="#">Generales</a>
                            <ul class="dropdown-menu">
                                <li><g:link controller="rsGralAsentamiento">Asentamiento</g:link></li>
                                <li><g:link controller="rsGralDelegacionMunicipio">Delegaci&oacute;n y Municipio</g:link></li>
                                <li><g:link controller="rsGralDomicilio">Domicilio</g:link></li>
                                <li><g:link controller="rsGralEstado">Estado</g:link></li>
                                <li><g:link controller="rsGralPais">Pa&iacute;s</g:link></li>
                                <li><g:link controller="rsGralTelefono">Tel&eacute;fono</g:link></li>
                                <li><g:link controller="rsPersona">Persona</g:link></li>
                            </ul>
                        </li>
                        <li class="divider"></li>
                        <li class="dropdown-submenu">
                            <a href="#">Cat&aacute;logo</a>
                            <ul class="dropdown-menu">
                                <li><g:link controller="rsCatEmpresa">Empresa</g:link></li>
                                <li><g:link controller="rsCatGrupoEmpresa">Grupo de la empresa</g:link></li>
                                <li><g:link controller="rsCatTipoAsentamiento">Tipo de asentamiento</g:link></li>
                                <li><g:link controller="rsCatTipoPersona">Tipo de persona</g:link></li>
                                <li><g:link controller="rsCatTipoTelefono">Tipo de tel&eacute;fono</g:link></li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mesa de Control</a>
            <ul class="dropdown-menu">
                <li><a href="#">Enalce 1</a></li>
                <li><a href="#">Enalce 2</a></li>
                <li><a href="#">Enalce 3</a></li>
                <li><a href="#">Enalce 4</a></li>
                <li><a href="#">Enalce 5</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pieza</a>
            <ul class="dropdown-menu">
                <li><a href="#">Enalce 1</a></li>
                <li><a href="#">Enalce 2</a></li>
                <li><a href="#">Enalce 3</a></li>
                <li><a href="#">Enalce 4</a></li>
                <li><a href="#">Enalce 5</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sucursal</a>
            <ul class="dropdown-menu">
                <li><a href="#">Enalce 1</a></li>
                <li><a href="#">Enalce 2</a></li>
                <li><a href="#">Enalce 3</a></li>
                <li><a href="#">Enalce 4</a></li>
                <li><a href="#">Enalce 5</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seguridad</a>
            <ul class="dropdown-menu">
                <li><g:link controller="user" action="search" >Usuarios</g:link></li>
                <li><g:link controller="role" action="search" >Roles</g:link></li>
                <li><g:link controller="requestmap" action="search" >URL's</g:link></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manuales</a>
            <ul class="dropdown-menu">
                <li><a href="#">Enalce 1</a></li>
                <li><a href="#">Enalce 2</a></li>
                <li><a href="#">Enalce 3</a></li>
                <li><a href="#">Enalce 4</a></li>
                <li><a href="#">Enalce 5</a></li>
            </ul>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <sec:ifNotLoggedIn>
            <li>
                <g:link controller='login' action='auth'><span class="glyphicon glyphicon-user"> Entrar</span></g:link>
            </li>
        </sec:ifNotLoggedIn>
        <sec:ifLoggedIn>
            <li class="active">
                <a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="#"><span class="glyphicon glyphicon-user"> ${usuario?.username}</span></a>
                <ul class="dropdown-menu" role="menu">
                    <li class="">
                        <g:link controller="logout">
                            <span class="glyphicon glyphicon-off"> <g:message code="security.signoff.label" default="Salir"/></span>
                        </g:link>
                    </li>
                </ul>
            </li>
        </sec:ifLoggedIn>

        <g:render template="/_menu/reloj"/>
    <%--
    <g:render template="/barraNavegacion/buscador"/>
    --%>
    </ul>
</div>

grails-app/views/_menu/_menubar.gsp
<div class="">
	<ul class="nav nav-tabs" data-role="listview" data-split-icon="gear" data-filter="true">
	
		<g:each status="i" var="c" in="${grailsApplication.controllerClasses.sort { it.logicalPropertyName } }">
			<li class="controller${params.controller == c.logicalPropertyName ? " active" : ""}">
				<g:link controller="${c.logicalPropertyName}" action="index">
					<g:message code="${c.logicalPropertyName}.label" default="${c.logicalPropertyName.capitalize()}"/>
				</g:link>
			</li>
		</g:each>
		
	</ul>
</div>

grails-app/views/_menu/_navbar.gsp
<nav id="Navbar" class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="${createLink(uri: '/')}" class="navbar-brand">
                <img src="${resource(dir: 'images', file: 'lithoTrack/LITHOtrack.png')}" />
            </a>
        </div>

        <div class="collapse navbar-collapse navbar-ex1-collapse" role="navigation">

            <ul class="nav navbar-nav navbar">
                <g:render template="/_menu/menu"/>

            </ul>

        </div>
    </div>
</nav>

grails-app/views/_menu/_reloj.gsp
<li class="">
    <a href="#" id="reloj">Hora Actual</a>
    <div id="horaActual"></div>
</li>


<script>
    $(document).ready(function(){
        dameTiempo();
    });

    function dameTiempo() {
        var fechaActual =   new Date();
        var horaActual  =   fechaActual.getDate() + " de " + dameMesLetra(fechaActual.getMonth()) + " de " + fechaActual.getFullYear() + " - " + dameDigitos(fechaActual.getHours()) + ":" + dameDigitos(fechaActual.getMinutes()) + ":" + dameDigitos(fechaActual.getSeconds());
        $('#reloj').text(horaActual);
        setTimeout(function(){dameTiempo()},500);
    }

    function dameMesLetra(mesNumero) {
        var mes = new Array();
        mes[0]="Enero";
        mes[1]="Febrero";
        mes[2]="Mazo";
        mes[3]="Abril";
        mes[4]="Mayo";
        mes[5]="Junio";
        mes[6]="Julio";
        mes[7]="Agosto";
        mes[8]="Septiembre";
        mes[9]="Octubre";
        mes[10]="Noviembre";
        mes[11]="Diciembre";

        return mes[mesNumero];
    }

    function dameDigitos(tiempo) {
        if (tiempo < 10) {
            tiempo = "0" + tiempo
        }
        return tiempo
    }
</script>

grails-app/views/_menu/_submenubar.gsp
<!-- 
This menu is used to show function that can be triggered on the content (an object or list of objects).
-->

<%-- Only show the "Pills" navigation menu if a controller exists (but not for home) --%>
<g:if test="${	params.controller != null
			&&	params.controller != ''
			&&	params.controller != 'home'
}">
	<ul id="Menu" class="nav nav-pills margin-top-small">

		<g:set var="entityName" value="${message(code: params.controller+'.label', default: params.controller.substring(0,1).toUpperCase() + params.controller.substring(1).toLowerCase())}" />
		
		<li class="${ params.action == "list" ? 'active' : '' }">
			<g:link action="list"><i class="glyphicon glyphicon-th-list"></i> <g:message code="default.list.label" args="[entityName]"/></g:link>
		</li>
		<li class="${ params.action == "create" ? 'active' : '' }">
			<g:link action="create"><i class="glyphicon glyphicon-plus"></i> <g:message code="default.new.label"  args="[entityName]"/></g:link>
		</li>
		
		<g:if test="${ params.action == 'show' || params.action == 'edit' }">
			<!-- the item is an object (not a list) -->
			<li class="${ params.action == "edit" ? 'active' : '' }">
				<g:link action="edit" id="${params.id}"><i class="glyphicon glyphicon-pencil"></i> <g:message code="default.edit.label"  args="[entityName]"/></g:link>
			</li>
			<li class="">
				<g:render template="/_common/modals/deleteTextLink"/>
			</li>
		</g:if>
		
	</ul>
</g:if>

grails-app/views/_menu/_user.gsp
<%@ page import="com.seguridad.Usuario" %>
<g:set var="usuario" value="${Usuario.findByUsername(sec.loggedInUserInfo(field:'username'))}"/>
<li class="dropdown">
    <sec:ifNotLoggedIn>
        <g:link controller="login">
            <i class="glyphicon glyphicon-user" class="dropdown-toggle" data-toggle="dropdown"></i>
            <g:message code="security.signin.label"/>
        </g:link>
    </sec:ifNotLoggedIn>

    <sec:ifLoggedIn>
        <a class="dropdown-toggle" role="button" data-toggle="dropdown" data-target="#" href="#">
            <i class="glyphicon glyphicon-user icon-white"></i>
            ${usuario?.username} <b class="caret"></b>
        </a>
        <ul class="dropdown-menu" role="menu">
            <li class="">
                <g:link controller="logout">
                    <i class="glyphicon glyphicon-off"></i>
                    <g:message code="security.signoff.label"/>
                </g:link>
            </li>
        </ul>
    </sec:ifLoggedIn>
</li>